---
efiBootLoader: "grub"
kernelSearchPath: "/usr/lib/modules"
kernelPattern: "^vmlinuz.*"
loaderEntries:
  - "timeout 5"
  - "default omni-os-*"
  - "console-mode keep"
kernelLine: ", with {}"
fallbackKernelLine: ", with {} (fallback initramfs)"
grubInstall: "/usr/bin/grub-install"
grubMkconfig: "/usr/bin/grub-mkconfig"
efiBootMgr: "/usr/bin/efibootmgr"
installEFIFallback: true
