---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512MiB
efiSystemPartitionName: "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - reuse

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
allowManualPartitioning:   true

initialPartitioningChoice: none
initialSwapChoice: hibernate

defaultFileSystemType:  "btrfs"
availableFileSystemTypes:  ["btrfs", "ext4"]

enableLuksFileChoice: true
luksEncryption: true
