---
services:
  - name: "NetworkManager"
    mandatory: true
  - name: "bluetooth"
    mandatory: false
  - name: "ollama"
    mandatory: true
  - name: "omni-hw-profiler.service"
    mandatory: true
  - name: "omni-observer.service"
    mandatory: true
  - name: "omni-neural-setup.service"
    mandatory: true
  - name: "omni-vram-manager.service"
    mandatory: true
  - name: "omni-medic.service"
    mandatory: true

  - name: "omni-action-bridge"
    mandatory: true
  - name: "apparmor"
    mandatory: false

targets:
  - name: "graphical"
    mandatory: true
