---
services:
  - name: "NetworkManager"
    mandatory: true
  - name: "bluetooth"
    mandatory: false
  - name: "ollama"
    mandatory: true
  - name: "omni-hw-profiler"
    mandatory: true
  - name: "omni-observer"
    mandatory: true
  - name: "omni-recall-daemon"
    mandatory: true
  - name: "omni-vram-manager"
    mandatory: true
  - name: "omni-neural-setup"
    mandatory: true
  - name: "apparmor"
    mandatory: false

targets:
  - name: "graphical"
    mandatory: true
