---
services:
  - name: "NetworkManager"
    mandatory: true
  - name: "bluetooth"
    mandatory: false
  - name: "ollama"
    mandatory: true
  - name: "omni-hw-profiler"
    mandatory: true
  - name: "omni-vram-manager"
    mandatory: true

  - name: "omni-action-bridge"
    mandatory: true
  - name: "apparmor"
    mandatory: false

targets:
  - name: "graphical"
    mandatory: true
