---
dontChroot: false
timeout: 900
script:
    - "-cp -a /etc/skel/. /home/${USER}/"
    - "-chown -R ${USER}:${USER} /home/${USER}"
    - "-chmod 700 /home/${USER}"
    - "-sed -i '/omni-installer.sh/d' /home/${USER}/.config/hypr/hyprland.conf"
    - "-snapper -c root create-config /"
    - "-mkinitcpio -p linux-zen"
    - "-mkinitcpio -p linux-lts"
    - "-mkinitcpio -p linux"
    - "-systemctl --global enable omni-observer.service"
    - "-systemctl --global enable omni-recall-daemon.service"
    - "-systemctl --global enable omni-recall-embedder.service"
    - "-systemctl --global enable omni-precacher.service"
