---
dontChroot: false
timeout: 900
script:
    - "-cp -a /etc/skel/. /home/${USER}/"
    - "-chown -R ${USER}:${USER} /home/${USER}"
    - "-chmod 700 /home/${USER}"
    - "-snapper -c root create-config /"
    - "-mkinitcpio -p linux-zen"
    - "-mkinitcpio -p linux-lts"
    - "-mkinitcpio -p linux"
