---
defaultGroups:
    - users
    - wheel
    - video
    - audio
    - input
    - storage
    - optical
    - network
    - lp
    - scanner

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true

userShell: /usr/bin/zsh
